language: generic

branches:
  only:
    - master
    - staging
    - production

sudo: required

services:
  - docker

env:
  - TARGET=a
  - TARGET=b
  - TARGET=c
  - TARGET=d

script:
  - bash build.sh $TARGET