language: generic

branches:
  only:
    - master
    - staging
    - production

sudo: required

services:
  - docker

env:
  - TARGET=a ANOTHER=hello
  - TARGET=b ANOTHER=hello
  - TARGET=c ANOTHER=hello
  - TARGET=d

script:
  - bash build.sh $TARGET